Support cross-layer KV cache sharing (#291)
* cross-layer kv cache sharing support

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* update comment

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* update comment

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* Fix the import issue caused by the previous renaming PR

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* Add parity check for FP8 KV cache cross-layer KV scales matching. Also removed sliding_window from the validator check.

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* Fix error: 'AttributeError: Mock object has no attribute 'impl''

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* support cross-layer kv cache sharing for batched RPA kernel

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* enfore _validate_shared_kv_cache_layout to check sliding_window attribute when it's hybrid model and also blocks when shared layer and its target layer don't agree on kv cache quantization(both the quant dtpye and the scales)

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* Removed stale extras from _ragged_paged_attention's func call

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

* Renamed the loop variable field to field_name to void the naming conflict

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>

---------

Signed-off-by: haotianx <ultraman.giantoflight@gmail.com>